# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [1]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [2]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['2' '2' '4.5' 'top' 'top' '2' '4.5' 'top' '4.5' 'top']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [4]:
# Місце для Вашого коду

print(np.random.choice(10))

7


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [7]:
# Місце для Вашого коду

t = np.matrix([[np.random.choice(10) for i in range(6)] for j in range(4)])
print(t)

[[0 1 8 1 0 1]
 [4 3 5 9 6 0]
 [0 7 7 3 0 1]
 [6 0 2 5 6 7]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [5]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[3 1 4 2 1 4 1 1 0 4]


Згенеруйте одну випадкову цифру.

In [9]:
# Місце для Вашого коду

print(np.random.randint(10))

5


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [10]:
# Місце для Вашого коду

t = np.matrix([[np.random.randint(10,99) for i in range(5)] for j in range(4)])
print(t)

[[78 96 87 82 39]
 [82 98 48 27 66]
 [74 17 92 23 80]
 [36 34 24 18 85]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [8]:
size = None
print(np.random.sample(size=size))

0.3369603119037976


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [12]:
# Місце для Вашого коду

t = np.matrix([[np.random.sample() for i in range(4)] for j in range(3)])
print(t)

[[0.62880334 0.88360395 0.12777946 0.74709575]
 [0.94683649 0.95404421 0.4491129  0.28130956]
 [0.12191174 0.91081926 0.44328292 0.61134051]]


Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [13]:
a = 3
b = 5

In [17]:
# Місце для Вашого коду
t = np.matrix([(b - a) * np.random.sample() + a for j in range(10)])
print(t)


[[4.11455364 4.83924967 4.1559253  3.47819874 3.23754889 4.52354144
  3.73070418 4.1623933  4.12591486 4.48508392]]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [12]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[9 5 3 7 8 1 0 2 6 4]


Перетасуйте матрицю $M$.

In [26]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
# Місце для Вашого коду

np.random.shuffle(M)
print(M)

[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [15]:
np.random.seed(42)

In [16]:
print(np.random.randint(10))

6


In [17]:
print(np.random.randint(10))

3


In [18]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [19]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [28]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'H' 'H' 'H' 'T' 'H' 'H' 'T' 'H']


In [29]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

8 heads and 2 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [30]:
# Місце для Вашого коду

tosses=np.random.choice(["H","T"],p=[p,1-p], size=100)
print(tosses)
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

['T' 'H' 'T' 'H' 'H' 'H' 'H' 'T' 'T' 'T' 'H' 'T' 'H' 'T' 'H' 'T' 'H' 'H'
 'T' 'T' 'H' 'T' 'H' 'H' 'H' 'T' 'H' 'H' 'H' 'T' 'T' 'H' 'H' 'T' 'T' 'H'
 'T' 'T' 'H' 'T' 'T' 'T' 'T' 'H' 'H' 'T' 'H' 'H' 'H' 'H' 'T' 'H' 'T' 'H'
 'H' 'T' 'T' 'H' 'T' 'T' 'T' 'H' 'H' 'T' 'T' 'H' 'T' 'H' 'H' 'H' 'H' 'H'
 'H' 'T' 'T' 'H' 'H' 'T' 'T' 'H' 'H' 'H' 'T' 'T' 'T' 'T' 'T' 'T' 'H' 'T'
 'H' 'T' 'T' 'H' 'H' 'T' 'T' 'T' 'H' 'H']
51 heads and 49 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [36]:
# Місце для Вашого коду
tosses=[np.random.randint(0,2) for i in range(100)]
print(tosses)
heads = tosses.count(1)
tails = tosses.count(0)

print("{} heads and {} tails".format(heads,tails))

[0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1]
49 heads and 51 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [42]:
# Місце для Вашого коду

a=0
b=2
tosses = [(b-a)*np.random.sample()+a for i in range(100)]
print(tosses)
heads=0
tails=0
for i in tosses:
    if i<1:
        heads+=1
    elif i>1:
        tails+=1

print("{} heads and {} tails".format(heads,tails))

[0.2679923463521223, 0.26877060664422725, 1.2242739207853612, 1.7735818453125984, 0.537486492571027, 1.550297147476159, 1.87845519451323, 0.4641937329371493, 0.7519837548888753, 0.32416516001372186, 1.3852384970572558, 1.6966489705996237, 1.8617005251190608, 1.3860386451577862, 1.5499623735531771, 0.5145277129160308, 0.7348089459386751, 0.3610395557932038, 1.1144923257050348, 0.11492192118623401, 1.6993477365075662, 1.1035175414412355, 0.9358471261955086, 0.5276379515194434, 0.7360506652876238, 1.8514802563091846, 0.5206329401597007, 0.44210996713307993, 1.8915375479775303, 1.7011153539918038, 1.7479063078577577, 1.6497440583104444, 0.13958465455828972, 0.6771572167272848, 1.7869969941855652, 0.5210339515126836, 0.38204281319567257, 1.329627378751953, 0.8595917752413516, 1.4884689891039493, 0.7471050159033557, 0.7943789897798257, 1.797878005647977, 1.9955859944921497, 0.9206835534710875, 0.49022735697218933, 1.1169951086190641, 1.7123011577438412, 1.4839637016241454, 1.709097700050405,

### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [46]:
# Місце для Вашого коду
for n in [10,50,100,250,500,1000,2500,5000,10000]:
    tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
    heads = list(tosses).count("H")
    tails = list(tosses).count("T")
    
    print("{} heads and {} tails probability: {}".format(heads,tails, heads/(n)))


7 heads and 3 tails probability: 0.7
26 heads and 24 tails probability: 0.52
49 heads and 51 tails probability: 0.49
131 heads and 119 tails probability: 0.524
253 heads and 247 tails probability: 0.506
497 heads and 503 tails probability: 0.497
1231 heads and 1269 tails probability: 0.4924
2494 heads and 2506 tails probability: 0.4988
5060 heads and 4940 tails probability: 0.506


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [49]:
# Місце для Вашого коду

tosses=np.random.choice(range(1,7), size=100)
print(tosses)
stats = [list(tosses).count(i) for i in range(1,7)]

print(stats)

[6 4 5 5 5 3 3 4 4 4 6 5 1 5 2 3 6 2 3 6 6 1 5 5 6 3 5 3 1 4 1 4 2 3 5 1 1
 1 6 2 4 4 2 2 6 5 6 3 6 3 4 5 6 6 3 3 2 6 2 3 4 6 6 4 1 5 5 3 4 2 5 5 1 5
 4 6 2 3 1 4 5 2 2 2 4 4 6 3 1 3 1 2 6 6 6 3 1 2 4 1]
[14, 15, 17, 17, 17, 20]


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [52]:
# Місце для Вашого коду

for n in [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]:
    tosses=np.random.choice(range(1,7), size=n)
    stats = [list(tosses).count(i) for i in range(1, 7)]
    print("stats {}, probability {}".format(stats, [i/n for i in stats]))
print(1/6)


stats [3, 3, 1, 1, 1, 1], probability [0.3, 0.3, 0.1, 0.1, 0.1, 0.1]
stats [7, 8, 9, 11, 7, 8], probability [0.14, 0.16, 0.18, 0.22, 0.14, 0.16]
stats [8, 19, 20, 23, 21, 9], probability [0.08, 0.19, 0.2, 0.23, 0.21, 0.09]
stats [42, 33, 40, 56, 44, 35], probability [0.168, 0.132, 0.16, 0.224, 0.176, 0.14]
stats [71, 85, 70, 93, 98, 83], probability [0.142, 0.17, 0.14, 0.186, 0.196, 0.166]
stats [150, 182, 156, 166, 189, 157], probability [0.15, 0.182, 0.156, 0.166, 0.189, 0.157]
stats [445, 412, 402, 416, 412, 413], probability [0.178, 0.1648, 0.1608, 0.1664, 0.1648, 0.1652]
stats [855, 822, 836, 811, 840, 836], probability [0.171, 0.1644, 0.1672, 0.1622, 0.168, 0.1672]
stats [1713, 1632, 1695, 1627, 1621, 1712], probability [0.1713, 0.1632, 0.1695, 0.1627, 0.1621, 0.1712]
0.16666666666666666


## 5 Колода карт
### 5.1 Реалізація

In [54]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('4', '♠'), ('4', '♡'), ('4', '♢'), ('4', '♣'), ('6', '♠'), ('6', '♡'), ('6', '♢'), ('6', '♣'), ('2', '♠'), ('2', '♡'), ('2', '♢'), ('2', '♣'), ('9', '♠'), ('9', '♡'), ('9', '♢'), ('9', '♣'), ('10', '♠'), ('10', '♡'), ('10', '♢'), ('10', '♣'), ('K', '♠'), ('K', '♡'), ('K', '♢'), ('K', '♣'), ('1', '♠'), ('1', '♡'), ('1', '♢'), ('1', '♣'), ('5', '♠'), ('5', '♡'), ('5', '♢'), ('5', '♣'), ('J', '♠'), ('J', '♡'), ('J', '♢'), ('J', '♣'), ('8', '♠'), ('8', '♡'), ('8', '♢'), ('8', '♣'), ('Q', '♠'), ('Q', '♡'), ('Q', '♢'), ('Q', '♣'), ('7', '♠'), ('7', '♡'), ('7', '♢'), ('7', '♣'), ('3', '♠'), ('3', '♡'), ('3', '♢'), ('3', '♣')]


In [31]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

3♣, 3♠, 3♡, 3♢, 7♣, 7♠, 7♡, 7♢, 9♣, 9♠, 9♡, 9♢, 5♣, 5♠, 5♡, 5♢, 6♣, 6♠, 6♡, 6♢, J♣, J♠, J♡, J♢, 4♣, 4♠, 4♡, 4♢, Q♣, Q♠, Q♡, Q♢, 8♣, 8♠, 8♡, 8♢, 10♣, 10♠, 10♡, 10♢, 1♣, 1♠, 1♡, 1♢, 2♣, 2♠, 2♡, 2♢, K♣, K♠, K♡, K♢


In [32]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♣3, ♣7, ♣9, ♣5, ♣6, ♣J, ♣4, ♣Q, ♣8, ♣10, ♣1, ♣2, ♣K
♠3, ♠7, ♠9, ♠5, ♠6, ♠J, ♠4, ♠Q, ♠8, ♠10, ♠1, ♠2, ♠K
♡3, ♡7, ♡9, ♡5, ♡6, ♡J, ♡4, ♡Q, ♡8, ♡10, ♡1, ♡2, ♡K
♢3, ♢7, ♢9, ♢5, ♢6, ♢J, ♢4, ♢Q, ♢8, ♢10, ♢1, ♢2, ♢K


In [33]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('Q', '♠'), ('10', '♡'), ('3', '♡'), ('2', '♠'), ('2', '♣'), ('10', '♢'), ('J', '♡'), ('1', '♢'), ('9', '♡'), ('3', '♣'), ('6', '♡'), ('Q', '♡'), ('K', '♣'), ('8', '♠'), ('J', '♠'), ('7', '♣'), ('K', '♡'), ('8', '♣'), ('5', '♣'), ('Q', '♢'), ('J', '♣'), ('J', '♢'), ('4', '♡'), ('1', '♡'), ('5', '♡'), ('5', '♢'), ('1', '♣'), ('1', '♠'), ('9', '♠'), ('10', '♣'), ('9', '♢'), ('2', '♢'), ('6', '♠'), ('Q', '♣'), ('10', '♠'), ('7', '♠'), ('2', '♡'), ('K', '♢'), ('8', '♢'), ('6', '♣'), ('K', '♠'), ('8', '♡'), ('7', '♢'), ('7', '♡'), ('4', '♢'), ('6', '♢'), ('3', '♠'), ('4', '♠'), ('9', '♣'), ('5', '♠'), ('4', '♣'), ('3', '♢')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [67]:
# Місце для Вашого коду
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)
for n in [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]:
    k = 0
    for i in range(n):
        t = Cards[np.random.randint(52)]
        try:
            if int(t[0])%2==0:
                k+=1
        except Exception:
            pass
    print("n= {} probability {}".format(str(n), str(k/n)))

[('4', '♠'), ('4', '♡'), ('4', '♢'), ('4', '♣'), ('6', '♠'), ('6', '♡'), ('6', '♢'), ('6', '♣'), ('2', '♠'), ('2', '♡'), ('2', '♢'), ('2', '♣'), ('9', '♠'), ('9', '♡'), ('9', '♢'), ('9', '♣'), ('10', '♠'), ('10', '♡'), ('10', '♢'), ('10', '♣'), ('K', '♠'), ('K', '♡'), ('K', '♢'), ('K', '♣'), ('1', '♠'), ('1', '♡'), ('1', '♢'), ('1', '♣'), ('5', '♠'), ('5', '♡'), ('5', '♢'), ('5', '♣'), ('J', '♠'), ('J', '♡'), ('J', '♢'), ('J', '♣'), ('8', '♠'), ('8', '♡'), ('8', '♢'), ('8', '♣'), ('Q', '♠'), ('Q', '♡'), ('Q', '♢'), ('Q', '♣'), ('7', '♠'), ('7', '♡'), ('7', '♢'), ('7', '♣'), ('3', '♠'), ('3', '♡'), ('3', '♢'), ('3', '♣')]
n= 10 probability 0.4
n= 50 probability 0.42
n= 100 probability 0.42
n= 250 probability 0.316
n= 500 probability 0.42
n= 1000 probability 0.368
n= 2500 probability 0.3764
n= 5000 probability 0.3948
n= 10000 probability 0.3777


### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [35]:
# Місце для Вашого коду



### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [36]:
# Місце для Вашого коду

